name: draggable_button_panel
description:
  The DraggableButtonPanel is a widget displaying a button with a movable panel of options. 
  When clicked, it animates the panel's appearance. 
  Customizable in color, size, and opacity. 
  Implements StatefulWidget, AnimationController, AnimatedOpacity, Stack, and Positioned. Ideal for Flutter apps.

version: 1.0.0-dev.2

environment:
  sdk: ">=3.0.0-218.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# Add any additional dependencies here:
# dependency_name: ^version

# The following section is specific to the package.
# It describes the author, homepage, and repository of the package.
# Replace <your name> and <your GitHub account> with your own information.

homepage: https://github.com/KsarKev/draggable_button_panel
repository: https://github.com/KsarKev/draggable_button_panel.git
